openapi: '3.0.0'
info:
  title: Phu chinh
  description: This API for letro intergration
  version: 1.0.0
  license:
    url: https://service.aainc.co.jp/product/letro/
    name: Letro intergration
servers:
  - url: 'https://letro-dev.com/advertiser'
    description: Local Server
  - url: 'https://stg.letro.jp/advertiser'
    description: Staging Server
  - url: 'https://letro.jp/advertiser'
    description: Production Server
tags:
  - name: Incentive
    description: Api for incentive. Incentive common and Incentive person
  - name: Import
    description: Api for screen import . Api for import customer , product , order
paths:
  '/incentive':
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  tag:
                    type: string

